export const MAJOR_CITIES = [
  "Ahmedabad",
  "Amritsar",
  "Aurangabad",
  "Bengaluru",
  "Bhopal",
  "Bhubaneswar",
  "Chandigarh",
  "Chennai",
  "Coimbatore",
  "Dehradun",
  "Delhi",
  "Durgapur",
  "Faridabad",
  "Ghaziabad",
  "Gurugram",
  "Guwahati",
  "Gwalior",
  "Hyderabad",
  "Indore",
  "Jaipur",
  "Jalandhar",
  "Jammu",
  "Jamshedpur",
  "Jodhpur",
  "Kanpur",
  "Kochi",
  "Kolkata",
  "Lucknow",
  "Ludhiana",
  "Madurai",
  "Meerut",
  "Mumbai",
  "Mysuru",
  "Nagpur",
  "Navi Mumbai",
  "Noida",
  "Patna",
  "Pimpri-Chinchwad",
  "Pune",
  "Raipur",
  "Rajkot",
  "Ranchi",
  "Surat",
  "Thane",
  "Tiruchirappalli",
  "Trivandrum",
  "Vadodara",
  "Varanasi",
  "Vijayawada",
  "Visakhapatnam",
];


export const statusColor: Record<string, string> = {
  pending: "bg-yellow-100 text-yellow-700",
  optimized: "bg-emerald-100 text-emerald-700",
  waiting: "bg-orange-100 text-orange-700", 
  available: "bg-yellow-100 text-yellow-700",
  booked: "bg-blue-100 text-blue-700",
  in_transit: "bg-purple-100 text-purple-700",
  delivered: "bg-green-100 text-green-700",
  cancelled: "bg-red-100 text-red-700",
};


// const statusColor: Record<string, string> = {
//   pending: "bg-yellow-100 text-yellow-700",
//   optimized: "bg-green-100 text-green-700",
//   booked: "bg-blue-100 text-blue-700",
//   in_transit: "bg-purple-100 text-purple-700",
//   delivered: "bg-emerald-100 text-emerald-700",
//   cancelled: "bg-red-100 text-red-700",
// };